library(dplyr)
dat<-read.table('household_power_consumption.txt',sep=';',header=TRUE, stringsAsFactors=FALSE)
dat<-filter(dat,Date=='1/2/2007'|Date=='2/2/2007')
dat$Date<-as.Date(dat$Date,format='%d/%m/%Y')
t<-strptime(paste(dat$Date,dat$Time),'%Y-%m-%d %H:%M:%S')
x11()
plot(t,dat$Global_active_power,type='l',ylab='Global Active Power (kilowatts)',xlab='')
dev.copy(png,file='figure/plot2.png')
dev.off()